# version: "3.9"

services:
  user_db:
    image: postgres:16
    container_name: eco_user_db
    environment:
      POSTGRES_USER: eco_user
      POSTGRES_PASSWORD: eco_user@1234
      POSTGRES_DB: eco_user
    ports:
      - "6000:5432"
    volumes:
      - eco_user_db_data:/var/lib/postgresql/data

  

volumes:
  eco_user_db_data: